rename rbenv to goenv

diff --git a/libexec/goenv b/libexec/goenv
--- a/libexec/goenv
+++ b/libexec/goenv
@@ -14,7 +14,7 @@ fi
 
 READLINK=$(type -p greadlink readlink | head -1)
 if [ -z "$READLINK" ]; then
-  echo "rbenv: cannot find readlink - are you missing GNU coreutils?" >&2
+  echo "goenv: cannot find readlink - are you missing GNU coreutils?" >&2
   exit 1
 fi
 
@@ -37,7 +37,7 @@ abs_dirname() {
 }
 
 if [ -z "${GOENV_ROOT}" ]; then
-  GOENV_ROOT="${HOME}/.rbenv"
+  GOENV_ROOT="${HOME}/.goenv"
 else
   GOENV_ROOT="${GOENV_ROOT%/}"
 fi
@@ -47,7 +47,7 @@ if [ -z "${GOENV_DIR}" ]; then
   GOENV_DIR="$(pwd)"
 else
   cd "$GOENV_DIR" 2>/dev/null || {
-    echo "rbenv: cannot change working directory to \`$GOENV_DIR'"
+    echo "goenv: cannot change working directory to \`$GOENV_DIR'"
     exit 1
   } >&2
   GOENV_DIR="$(pwd)"
@@ -64,8 +64,8 @@ for plugin_bin in "${GOENV_ROOT}/plugins/"*/bin; do
 done
 export PATH="${bin_path}:${PATH}"
 
-hook_path="${RBENV_HOOK_PATH}:${GOENV_ROOT}/rbenv.d:/usr/local/etc/rbenv.d:/etc/rbenv.d:/usr/lib/rbenv/hooks"
-for plugin_hook in "${GOENV_ROOT}/plugins/"*/etc/rbenv.d; do
+hook_path="${RBENV_HOOK_PATH}:${GOENV_ROOT}/goenv.d:/usr/local/etc/goenv.d:/etc/goenv.d:/usr/lib/goenv/hooks"
+for plugin_hook in "${GOENV_ROOT}/plugins/"*/etc/goenv.d; do
   hook_path="${hook_path}:${plugin_hook}"
 done
 export RBENV_HOOK_PATH="$hook_path"
@@ -76,15 +76,15 @@ shopt -u nullglob
 command="$1"
 case "$command" in
 "" | "-h" | "--help" )
-  echo -e "$(rbenv---version)\n$(rbenv-help)" >&2
+  echo -e "$(goenv---version)\n$(goenv-help)" >&2
   ;;
 "-v" )
-  exec rbenv---version
+  exec goenv---version
   ;;
 * )
-  command_path="$(command -v "rbenv-$command" || true)"
+  command_path="$(command -v "goenv-$command" || true)"
   if [ -z "$command_path" ]; then
-    echo "rbenv: no such command \`$command'" >&2
+    echo "goenv: no such command \`$command'" >&2
     exit 1
   fi
 
diff --git a/libexec/goenv-hooks b/libexec/goenv-hooks
--- a/libexec/goenv-hooks
+++ b/libexec/goenv-hooks
@@ -1,11 +1,11 @@
 #!/usr/bin/env bash
-# Summary: List hook scripts for a given rbenv command
-# Usage: rbenv hooks <command>
+# Summary: List hook scripts for a given goenv command
+# Usage: goenv hooks <command>
 
 set -e
 [ -n "$GOENV_DEBUG" ] && set -x
 
-# Provide rbenv completions
+# Provide goenv completions
 if [ "$1" = "--complete" ]; then
   echo exec
   echo rehash
@@ -15,13 +15,13 @@ fi
 
 RBENV_COMMAND="$1"
 if [ -z "$RBENV_COMMAND" ]; then
-  rbenv-help --usage hooks >&2
+  goenv-help --usage hooks >&2
   exit 1
 fi
 
 READLINK=$(type -p greadlink readlink | head -1)
 if [ -z "$READLINK" ]; then
-  echo "rbenv: cannot find readlink - are you missing GNU coreutils?" >&2
+  echo "goenv: cannot find readlink - are you missing GNU coreutils?" >&2
   exit 1
 fi
 
diff --git a/libexec/goenv-init b/libexec/goenv-init
--- a/libexec/goenv-init
+++ b/libexec/goenv-init
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
-# Summary: Configure the shell environment for rbenv
-# Usage: eval "$(rbenv init - [--no-rehash] [<shell>])"
+# Summary: Configure the shell environment for goenv
+# Usage: eval "$(goenv init - [--no-rehash] [<shell>])"
 
 set -e
 [ -n "$GOENV_DEBUG" ] && set -x
@@ -30,7 +30,7 @@ fi
 
 READLINK=$(type -p greadlink readlink | head -1)
 if [ -z "$READLINK" ]; then
-  echo "rbenv: cannot find readlink - are you missing GNU coreutils?" >&2
+  echo "goenv: cannot find readlink - are you missing GNU coreutils?" >&2
   exit 1
 fi
 
@@ -73,15 +73,15 @@ if [ -z "$print" ]; then
     ;;
   esac
 
-  { echo "# Load rbenv automatically by adding"
+  { echo "# Load goenv automatically by adding"
     echo "# the following to ${profile}:"
     echo
     case "$shell" in
     fish )
-      echo 'status --is-interactive; and . (rbenv init -|psub)'
+      echo 'status --is-interactive; and . (goenv init -|psub)'
       ;;
     * )
-      echo 'eval "$(rbenv init -)"'
+      echo 'eval "$(goenv init -)"'
       ;;
     esac
     echo
@@ -112,7 +112,7 @@ fish )
 ;;
 esac
 
-completion="${root}/completions/rbenv.${shell}"
+completion="${root}/completions/goenv.${shell}"
 if [ -r "$completion" ]; then
   case "$shell" in
   fish ) echo ". '$completion'" ;;
@@ -121,22 +121,22 @@ if [ -r "$completion" ]; then
 fi
 
 if [ -z "$no_rehash" ]; then
-  echo 'rbenv rehash 2>/dev/null'
+  echo 'goenv rehash 2>/dev/null'
 fi
 
-commands=(`rbenv-commands --sh`)
+commands=(`goenv-commands --sh`)
 case "$shell" in
 fish )
   cat <<EOS
-function rbenv
+function goenv
   set command \$argv[1]
   set -e argv[1]
 
   switch "\$command"
   case ${commands[*]}
-    eval (rbenv "sh-\$command" \$argv)
+    eval (goenv "sh-\$command" \$argv)
   case '*'
-    command rbenv "\$command" \$argv
+    command goenv "\$command" \$argv
   end
 end
 EOS
@@ -144,13 +144,13 @@ EOS
   ;;
 ksh )
   cat <<EOS
-function rbenv {
+function goenv {
   typeset command
 EOS
   ;;
 * )
   cat <<EOS
-rbenv() {
+goenv() {
   local command
 EOS
   ;;
@@ -165,9 +165,9 @@ cat <<EOS
 
   case "\$command" in
   ${commands[*]})
-    eval "\`rbenv "sh-\$command" "\$@"\`";;
+    eval "\`goenv "sh-\$command" "\$@"\`";;
   *)
-    command rbenv "\$command" "\$@";;
+    command goenv "\$command" "\$@";;
   esac
 }
 EOS
diff --git a/libexec/goenv-prefix b/libexec/goenv-prefix
--- a/libexec/goenv-prefix
+++ b/libexec/goenv-prefix
@@ -1,40 +1,40 @@
 #!/usr/bin/env bash
 # Summary: Display prefix for a Ruby version
-# Usage: rbenv prefix [<version>]
+# Usage: goenv prefix [<version>]
 #
 # Displays the directory where a Ruby version is installed. If no
-# version is given, `rbenv prefix' displays the location of the
+# version is given, `goenv prefix' displays the location of the
 # currently selected version.
 
 set -e
 [ -n "$GOENV_DEBUG" ] && set -x
 
-# Provide rbenv completions
+# Provide goenv completions
 if [ "$1" = "--complete" ]; then
   echo system
-  exec rbenv-versions --bare
+  exec goenv-versions --bare
 fi
 
 if [ -n "$1" ]; then
   export RBENV_VERSION="$1"
 elif [ -z "$RBENV_VERSION" ]; then
-  RBENV_VERSION="$(rbenv-version-name)"
+  RBENV_VERSION="$(goenv-version-name)"
 fi
 
 if [ "$RBENV_VERSION" = "system" ]; then
-  if RUBY_PATH="$(rbenv-which ruby 2>/dev/null)"; then
+  if RUBY_PATH="$(goenv-which ruby 2>/dev/null)"; then
     RUBY_PATH="${RUBY_PATH%/*}"
     echo "${RUBY_PATH%/bin}"
     exit
   else
-    echo "rbenv: system version not found in PATH" >&2
+    echo "goenv: system version not found in PATH" >&2
     exit 1
   fi
 fi
 
 RBENV_PREFIX_PATH="${GOENV_ROOT}/versions/${RBENV_VERSION}"
 if [ ! -d "$RBENV_PREFIX_PATH" ]; then
-  echo "rbenv: version \`${RBENV_VERSION}' not installed" >&2
+  echo "goenv: version \`${RBENV_VERSION}' not installed" >&2
   exit 1
 fi
 
diff --git a/libexec/goenv-which b/libexec/goenv-which
--- a/libexec/goenv-which
+++ b/libexec/goenv-which
@@ -2,17 +2,17 @@
 #
 # Summary: Display the full path to an executable
 #
-# Usage: rbenv which <command>
+# Usage: goenv which <command>
 #
-# Displays the full path to the executable that rbenv will invoke when
+# Displays the full path to the executable that goenv will invoke when
 # you run the given command.
 
 set -e
 [ -n "$GOENV_DEBUG" ] && set -x
 
-# Provide rbenv completions
+# Provide goenv completions
 if [ "$1" = "--complete" ]; then
-  exec rbenv shims --short
+  exec goenv shims --short
 fi
 
 expand_path() {
@@ -48,11 +48,11 @@ remove_from_path() {
   echo "${result%:}"
 }
 
-RBENV_VERSION="$(rbenv-version-name)"
+RBENV_VERSION="$(goenv-version-name)"
 RBENV_COMMAND="$1"
 
 if [ -z "$RBENV_COMMAND" ]; then
-  rbenv-help --usage which >&2
+  goenv-help --usage which >&2
   exit 1
 fi
 
@@ -64,7 +64,7 @@ else
 fi
 
 OLDIFS="$IFS"
-IFS=$'\n' scripts=(`rbenv-hooks which`)
+IFS=$'\n' scripts=(`goenv-hooks which`)
 IFS="$OLDIFS"
 for script in "${scripts[@]}"; do
   source "$script"
@@ -73,9 +73,9 @@ done
 if [ -x "$RBENV_COMMAND_PATH" ]; then
   echo "$RBENV_COMMAND_PATH"
 else
-  echo "rbenv: $RBENV_COMMAND: command not found" >&2
+  echo "goenv: $RBENV_COMMAND: command not found" >&2
 
-  versions="$(rbenv-whence "$RBENV_COMMAND" || true)"
+  versions="$(goenv-whence "$RBENV_COMMAND" || true)"
   if [ -n "$versions" ]; then
     { echo
       echo "The \`$1' command exists in these Ruby versions:"
